SystemOrganization addCategory: 'Monticello-Base'!
SystemOrganization addCategory: 'Monticello-Chunk Format'!
SystemOrganization addCategory: 'Monticello-Gemstone'!
SystemOrganization addCategory: 'Monticello-Loading'!
SystemOrganization addCategory: 'Monticello-Merging'!
SystemOrganization addCategory: 'Monticello-Mocks'!
SystemOrganization addCategory: 'Monticello-Modeling'!
SystemOrganization addCategory: 'Monticello-Patching'!
SystemOrganization addCategory: 'Monticello-Platform'!
SystemOrganization addCategory: 'Monticello-Repositories'!
SystemOrganization addCategory: 'Monticello-Storing'!
SystemOrganization addCategory: 'Monticello-Tests'!
SystemOrganization addCategory: 'Monticello-Tests-Gemstone'!
SystemOrganization addCategory: 'Monticello-Versioning'!
